platform :ios, '9.0'

target 'GuideWay' do
  use_frameworks!

  pod 'AsyncDisplayKit/IGListKit'
  pod 'DITranquillity'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Siesta'
  pod 'ObjectMapper'
  pod 'GoogleMaps'
  pod 'NVActivityIndicatorView'
end
